#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
DROPLET_IP="208.68.36.209"

banner "FlipFlop HQ: domain + DNS for TLS"

# ── Stage 1: buy a domain ─────────────────────────────────────────────────
stage "Register a domain"
say "Let's Encrypt won't issue a certificate for a bare IP, so the droplet"
say "needs a real hostname. Any registrar works. Three that are cheap and"
say "have no upsell traps; pick one, or use one you already have:"
open_url "https://porkbun.com"
open_url "https://www.namecheap.com/domains/"
open_url "https://www.cloudflare.com/products/registrar/"
step "Search for the name you want and buy it. A .com or .io is fine; a"
step "cheap TLD like .xyz is fine too — the certificate doesn't care."
note "If it offers WHOIS privacy, take it (usually free)."
ask FLIPFLOP_DOMAIN "Domain you registered (e.g. flipflophq.com):"
FLIPFLOP_DOMAIN="${FLIPFLOP_DOMAIN,,}"
FLIPFLOP_DOMAIN="${FLIPFLOP_DOMAIN#http://}"; FLIPFLOP_DOMAIN="${FLIPFLOP_DOMAIN#https://}"
FLIPFLOP_DOMAIN="${FLIPFLOP_DOMAIN%%/*}"
write_env FLIPFLOP_DOMAIN "$FLIPFLOP_DOMAIN"

# ── Stage 2: point it at the droplet ──────────────────────────────────────
stage "Point DNS at the droplet"
say "In your registrar's DNS settings for $FLIPFLOP_DOMAIN, add one record:"
say ""
say "    Type:   A"
say "    Host:   @        (some registrars call this 'Name' or leave it blank)"
say "    Value:  $DROPLET_IP"
say "    TTL:    lowest available (300 / 5 min / 'Automatic')"
say ""
note "Every registrar's DNS page looks different, so this wizard can't click"
note "it for you. Look for 'DNS', 'DNS Records', 'Advanced DNS', or 'Manage DNS'."
warn "If the registrar pre-created a parking A record or URL redirect for @,"
warn "delete it — only one A record for @ should exist, pointing at the droplet."
pause "Press Enter once the record is saved."

say "Watching for $FLIPFLOP_DOMAIN to resolve to $DROPLET_IP …"
note "New records usually propagate in 1–10 minutes; some registrars take up to an hour."
_resolve() {
  if command -v dig >/dev/null 2>&1; then
    dig +short "$1" A 2>/dev/null | tail -n1
  else
    nslookup "$1" 2>/dev/null | awk '/^Address/ {a=$2} END {print a}'
  fi
}
until [[ "$(_resolve "$FLIPFLOP_DOMAIN")" == "$DROPLET_IP" ]]; do
  note "  not yet ($(_resolve "$FLIPFLOP_DOMAIN" || echo 'no answer')). Retrying in 30s — Ctrl-C to stop and re-run later."
  sleep 30
done
printf '  %s✓ %s resolves to %s%s\n' "$GREEN" "$FLIPFLOP_DOMAIN" "$DROPLET_IP" "$RESET"

# ── Stage 3: certificate contact + terms ──────────────────────────────────
stage "Let's Encrypt contact"
say "Let's Encrypt emails this address before a certificate expires. Renewal"
say "is automatic, so you'd only ever hear from them if renewal broke."
ask LETSENCRYPT_EMAIL "Email for expiry notices:"
write_env LETSENCRYPT_EMAIL "$LETSENCRYPT_EMAIL"
say ""
say "Issuing a certificate means agreeing to the Let's Encrypt Subscriber"
say "Agreement on your behalf. Read it here if you like:"
open_url "https://letsencrypt.org/repository/"
confirm "Agree to the Let's Encrypt Subscriber Agreement?" || {
  warn "TLS can't be set up without agreeing. Nothing else was changed."
  exit 1
}
write_env LETSENCRYPT_TOS_AGREED "yes"

# ──────────────────────────────────────────────────────────────────────────

finish
say "Next: tell Claude the wizard finished. It reads $ENV_FILE and runs"
say "tls_vps.sh over SSH to issue the certificate and switch nginx to HTTPS."
printf '\n'
